FROM alpine/git
WORKDIR /app
RUN git clone https://github.com/cameronmcnz/rock-paper-scissors.git
FROM maven:3.5-jdk-8-alpine
WORKDIR /app
COPY --from=0 /app/rock-paper-scissors /app 
RUN mvn install 
FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=1 /app/target/rock-paper-scissors-1.5.1.jar /app 
CMD ["java -jar spring-petclinic-1.5.1.jar"] 
